about: {home: 'https://github.com/numba/llvmlite', license: New BSD License, summary: A
    lightweight LLVM python binding for writing JIT compilers}
build:
  entry_points: []
  features: []
  number: 0
  script_env: []
  string: ''
  track_features: []
package: {name: llvmlite, version: 0.5.0}
requirements:
  build: [python, llvmdev 3.5.1p1, enum34]
  conflicts: []
  run: [python, enum34]
source:
  git_rev: ''
  git_url: https://github.com/numba/llvmlite.git
  md5: ''
  patches: []
  path: ''
  svn_rev: ''
test:
  commands: []
  files: []
  imports: [llvmlite, llvmlite.binding]
  requires: []
